name: 'sql_neural_network'
version: '1.0.0'
config-version: 2

profile: 'sql_neural_network'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Model configurations
models:
  sql_neural_network:
    # Databricks implementation (recommended)
    databricks:
      +materialized: table
      +tags: ['databricks', 'neural_network']
    
    # Snowflake implementation
    snowflake:
      +materialized: table
      +tags: ['snowflake', 'neural_network']
    
    # Wide format implementation (database-agnostic)
    wide:
      +materialized: table
      +tags: ['wide_format', 'neural_network']

# Seed configurations
seeds:
  sql_neural_network:
    # Specific column types for different seed patterns
    fc1_bias:
      +column_types:
        output_idx: int
        bias_value: float
    fc2_bias:
      +column_types:
        output_idx: int
        bias_value: float
    fc3_bias:
      +column_types:
        output_idx: int
        bias_value: float
    
    # Row format weights (for wide SQL)
    fc1_weight:
      +column_types:
        output_idx: int
        input_idx: int
        weight_value: float
    fc2_weight:
      +column_types:
        output_idx: int
        input_idx: int
        weight_value: float
    fc3_weight:
      +column_types:
        output_idx: int
        input_idx: int
        weight_value: float
    
    # Array format weights (Databricks & Snowflake)
    fc1_weights_databricks:
      +column_types:
        output_idx: int
        weights: string
    fc2_weights_databricks:
      +column_types:
        output_idx: int
        weights: string
    fc3_weights_databricks:
      +column_types:
        output_idx: int
        weights: string
    fc1_weights_snowflake:
      +column_types:
        output_idx: int
        weights: string
    fc2_weights_snowflake:
      +column_types:
        output_idx: int
        weights: string
    fc3_weights_snowflake:
      +column_types:
        output_idx: int
        weights: string
    
    # Input data
    input_images:
      +column_types:
        sample_id: int
        pixel_idx: int
        pixel_value: float
    true_labels:
      +column_types:
        sample_id: int
        true_label: int
